init:
  - ps: "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 + [Net.SecurityProtocolType]::Tls11 + [Net.SecurityProtocolType]::Tls"
  - ps: Update-Module -Name PowerShellGet -Force -ErrorAction SilentlyContinue
  - ps: Install-Module -Name PhpManager -Repository PSGallery -Scope AllUsers -Force
  - ps: Install-Php -Version '7.2' -Architecture x64 -ThreadSafe $false -Path C:\PHP -TimeZone UTC -AddToPath System -InitialPhpIni Production -InstallVC -Force
build: 'off'
test_script:
  - ps: |
     .\test\online\driver.ps1 'appveyor'
     if ($Env:APPVEYOR_REPO_TAG -eq 'true') {
       .\test\online\tag.ps1 $Env:APPVEYOR_REPO_COMMIT $Env:APPVEYOR_REPO_TAG_NAME
     } elseif ($Env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT) {
       .\test\online\pr.ps1 $Env:APPVEYOR_REPO_COMMIT $Env:APPVEYOR_REPO_BRANCH '' $Env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT ''
     } elseif ($Env:APPVEYOR_SCHEDULED_BUILD) {
       .\test\online\cron.ps1 $Env:APPVEYOR_REPO_COMMIT $Env:APPVEYOR_REPO_BRANCH
     } elseif ($Env:APPVEYOR_FORCED_BUILD) {
       .\test\online\manual.ps1 $Env:APPVEYOR_REPO_COMMIT $Env:APPVEYOR_REPO_BRANCH
     } else {
       .\test\online\push.ps1 $Env:APPVEYOR_REPO_COMMIT $Env:APPVEYOR_REPO_BRANCH '' 'provide a way to detect the previous commit of a push event'
     }
