notifications:
  email: false
language: php
php: '7.2'
before_install:
  - phpenv config-rm xdebug.ini || true
after_failure:
  - set | grep -E '^(TRAVIS|CI)'
  - git log --format=oneline --max-count=20
matrix:
  fast_finish: true
  include:
    - name: Test pull request events
      if: type = pull_request
      script: |
        ./test/online/driver travis-ci
        ./test/online/pr "$TRAVIS_COMMIT" "$TRAVIS_BRANCH" '' "$TRAVIS_PULL_REQUEST_SHA" "${TRAVIS_COMMIT_RANGE:-}"
    - name: Test push events
      if: type = push AND tag is blank
      script: |
        ./test/online/driver travis-ci
        if test -n "${TRAVIS_COMMIT_RANGE:-}" && test "${TRAVIS_COMMIT_RANGE%^*}" = "${TRAVIS_COMMIT_RANGE:-}"; then
          ./test/online/push "$TRAVIS_COMMIT" "$TRAVIS_BRANCH" "${TRAVIS_COMMIT_RANGE%...*}" ''
        else
          ./test/online/push "$TRAVIS_COMMIT" "$TRAVIS_BRANCH" '' ''
        fi
    - name: Test tag events
      if: tag is present
      script: |
        ./test/online/driver travis-ci
        ./test/online/tag "$TRAVIS_COMMIT" "$TRAVIS_TAG"
    - name: Test API events
      if: type = api
      script: |
        ./test/online/driver travis-ci
        ./test/online/manual "$TRAVIS_COMMIT" "$TRAVIS_BRANCH"
    - name: Test cron events
      if: type = cron
      script: |
        ./test/online/driver travis-ci
        ./test/online/cron "$TRAVIS_COMMIT" "$TRAVIS_BRANCH"
