notifications:
  email: false
language: php
php: '7.2'
before_install:
  - phpenv config-rm xdebug.ini || true
after_failure:
  - set | grep -E '^(TRAVIS|CI)'
matrix:
  fast_finish: true
  include:
    - name: Test detected driver
      script: test "$(./bin/ci-info driver)" = 'travis-ci'
    - name: Test pull request events
      if: type = pull_request
      script: |
        test "$(./bin/ci-info event)" = 'pull-request'
        test "$(./bin/ci-info sha1)" = "$TRAVIS_COMMIT"
        test "$(./bin/ci-info pr:base:branch)" = "$TRAVIS_BRANCH"
        baseSha1="$(./bin/ci-info pr:base:sha1)"
        headSha1="$(./bin/ci-info pr:head:sha1)"
        range="$(./bin/ci-info pr:range)"
        php -r 'exit(preg_match("/^[0-9a-f]{40}$/i", $argv[1]) ? 0 : 1);' "$baseSha1"
        php -r 'exit(preg_match("/^[0-9a-f]{40}$/i", $argv[1]) ? 0 : 1);' "$headSha1"
        php -r 'exit(preg_match("/^[0-9a-f]{40}\.\.\.[0-9a-f]{40}$/i", $argv[1]) ? 0 : 1);' "$range"
        if test -n "${TRAVIS_COMMIT_RANGE:-}"; then
          test "$baseSha1...$headSha1" = "$TRAVIS_COMMIT_RANGE"
          test "$range" = "$TRAVIS_COMMIT_RANGE"
        fi
    - name: Test push events
      if: type = push AND tag is blank
      script: |
        test "$(./bin/ci-info event)" = 'push'
        test "$(./bin/ci-info sha1)" = "$TRAVIS_COMMIT"
    - name: Test tag events
      if: tag is present
      script: |
        test "$(./bin/ci-info event)" = 'tag'
        test "$(./bin/ci-info sha1)" = "$TRAVIS_COMMIT"
        test "$(./bin/ci-info tag:name)" = "$TRAVIS_TAG"
    - name: Test API events
      if: type = api
      script: |
        test "$(./bin/ci-info event)" = 'manual'
        test "$(./bin/ci-info sha1)" = "$TRAVIS_COMMIT"
    - name: Test cron events
      if: type = cron
      script: |
        test "$(./bin/ci-info event)" = 'scheduled'
        test "$(./bin/ci-info sha1)" = "$TRAVIS_COMMIT"
