name: Check Coding Style

on:
  pull_request:

jobs:
  php:
    name: PHP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          extensions: 'mbstring, openssl, zip'
          tools: 'composer:v1'
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --optimize-autoloader --no-ansi --no-interaction
      - name: Check
        run: composer run-script phpcs -- --dry-run --using-cache=no --diff --diff-format=udiff --show-progress=none --verbose --no-interaction --ansi .
  powershell:
    name: PowerShell
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install PSScriptAnalyzer
        run: Install-Module -Name PSScriptAnalyzer -Force
      - name: Check
        run: Invoke-ScriptAnalyzer -Path . -Recurse -EnableExit -Settings .\PSScriptAnalyzerSettings.psd1
  posix:
    name: POSIX Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Check with ShellCheck
        run: docker run --rm -v "$GITHUB_WORKSPACE:/app" -w /app koalaman/shellcheck:v0.7.1 .github/workflows/update-readme $(find ./test/online -type f ! -name "*.*")
      - name: Check with shfmt
        run: docker run --rm -v "$GITHUB_WORKSPACE:/app" -w /app mvdan/shfmt:v3.1.2 -d -ln=posix -i 4 -ci .github/workflows/update-readme $(find ./test/online -type f ! -name "*.*")
