name: Online Tests

on:
  create:
  pull_request:
  push:
    branches: '*'
  schedule:
  - cron: '0 8 * * *'
  repository_dispatch:

jobs:
  test_posix:
    strategy:
      matrix:
        operating-system:
          - macos-latest
          - ubuntu-latest
        php-versions:
          - '7.2'
          - '7.3'
          - '7.4'
    name: PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    if: "!startsWith(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check driver
        run: ./test/online/driver 'github-actions'
      - name: Check pull_request events
        if: github.event_name == 'pull_request'
        env:
          EXPECTED_BASE_SHA1: ${{ github.event.pull_request.base.sha }}
          EXPECTED_HEAD_SHA1: ${{ github.event.pull_request.head.sha }}
        run: ./test/online/pr "$GITHUB_SHA" "$GITHUB_BASE_REF" "$EXPECTED_BASE_SHA1" "$EXPECTED_HEAD_SHA1" "$EXPECTED_BASE_SHA1...$EXPECTED_HEAD_SHA1"
      - name: Check push events (without GITHUB_CONTEXT)
        if: github.event_name == 'push'
        run: ./test/online/push "$GITHUB_SHA" "${GITHUB_REF#refs/heads/}" '' 'no built-in environment variables in GitHub Actions holding the previous commit of a push event'
      - name: Check push events (with GITHUB_CONTEXT)
        if: github.event_name == 'push'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          EXPECTED_PREV_SHA1: ${{ github.event.before }}
        run: ./test/online/push "$GITHUB_SHA" "${GITHUB_REF#refs/heads/}" "$EXPECTED_PREV_SHA1" ''
      - name: Check tag creation
        if: github.event_name == 'create'
        run: ./test/online/tag "$GITHUB_SHA" "${GITHUB_REF#refs/tags/}"
      - name: Check repository_dispatch events
        if: github.event_name == 'repository_dispatch'
        run: ./test/online/manual "$GITHUB_SHA" "${GITHUB_REF#refs/heads/}"
      - name: Check scheduled events
        if: github.event_name == 'schedule'
        run: ./test/online/cron "$GITHUB_SHA" "${GITHUB_REF#refs/heads/}"
      - name: List environment variables
        if: ${{ failure() }}
        run: set | grep -E '^(GITHUB|CI)'
  test_windows:
    strategy:
      matrix:
        operating-system:
          - windows-latest
        php-versions:
          - '7.2'
          - '7.3'
          - '7.4'
    name: PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check driver
        run: .\test\online\driver.ps1 'github-actions'
      - name: Check pull_request events
        if: github.event_name == 'pull_request'
        env:
          EXPECTED_BASE_SHA1: ${{ github.event.pull_request.base.sha }}
          EXPECTED_HEAD_SHA1: ${{ github.event.pull_request.head.sha }}
        run: .\test\online\pr.ps1 $Env:GITHUB_SHA $Env:GITHUB_BASE_REF $Env:EXPECTED_BASE_SHA1 $Env:EXPECTED_HEAD_SHA1 "$Env:EXPECTED_BASE_SHA1...$Env:EXPECTED_HEAD_SHA1"
      - name: Check push events (without GITHUB_CONTEXT)
        if: github.event_name == 'push'
        run: .\test\online\push.ps1 $Env:GITHUB_SHA $($Env:GITHUB_REF -replace '^refs/heads/','') '' 'no built-in environment variables in GitHub Actions holding the previous commit of a push event'
      - name: Check push events (with GITHUB_CONTEXT)
        if: github.event_name == 'push'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          EXPECTED_PREV_SHA1: ${{ github.event.before }}
        run: .\test\online\push.ps1 $Env:GITHUB_SHA $($Env:GITHUB_REF -replace '^refs/heads/','') $Env:EXPECTED_PREV_SHA1 ''
      - name: Check tag creation
        if: github.event_name == 'create'
        run: .\test\online\tag.ps1 $Env:GITHUB_SHA $($Env:GITHUB_REF -replace '^refs/tags/','')
      - name: Check repository_dispatch events
        if: github.event_name == 'repository_dispatch'
        run: .\test\online\manual.ps1 $Env:GITHUB_SHA $($Env:GITHUB_REF -replace '^refs/heads/','')
      - name: Check scheduled events
        if: github.event_name == 'schedule'
        run: .\test\online\cron.ps1 $Env:GITHUB_SHA $($Env:GITHUB_REF -replace '^refs/heads/','')
      - name: List environment variables
        if: ${{ failure() }}
        run: 'Get-ChildItem -LiteralPath Env: | Where-Object { $_.Name -match "^(GITHUB|CI)" }'
