name: Online Tests

on:
  create:
  pull_request:
  push:
   schedule:
    - cron:  '0 8 * * *'
  repository_dispatch:

jobs:
  test_posix:
    strategy:
      matrix:
        operating-system:
          - macos-latest
          - ubuntu-latest
        php-versions:
          - '7.2'
          - '7.3'
          - '7.4'
    name: PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    if: "!startsWith(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: 'composer:v1'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: composer install --no-dev --no-progress --no-suggest --classmap-authoritative --no-ansi --no-interaction
      - name: Configure environment
        run: |
          set -o errexit
      - name: Check engine
        run: |
          test "$(./bin/ci-info driver)" = 'github-actions'
      - name: Check tag creation
        if: github.event_name == 'create'
        run: |
          test "$(./bin/ci-info event)" = 'tag'
          test "$(./bin/ci-info sha1)" = "$GITHUB_SHA"
          test "$(./bin/ci-info tag;name)" = ${GITHUB_REF#refs/tags/}
      - name: Check pull_request events
        if: github.event_name == 'pull_request'
        run: |
          test "$(./bin/ci-info event)" = 'pull-request'
          test "$(./bin/ci-info sha1)" = "$GITHUB_SHA"
          range="$(./bin/ci-info pr:range)"
          echo "range='$range'"
          php -r 'exit(preg_match("/^[0-9a-f]{40}\.\.\.[0-9a-f]{40}$/i", $argv[1]) ? 0 : 1);' "$range"
      - name: Check push events
        if: github.event_name == 'push'
        run: |
          test "$(./bin/ci-info event)" = 'push'
          test "$(./bin/ci-info sha1)" = "$GITHUB_SHA"
      - name: Check scheduled events
        if: github.event_name == 'schedule'
        run: |
          test "$(./bin/ci-info event)" = 'scheduled'
          test "$(./bin/ci-info sha1)" = "$GITHUB_SHA"
      - name: Check repository_dispatch events
        if: github.event_name == 'repository_dispatch'
        run: |
          test "$(./bin/ci-info event)" = 'manual'
          test "$(./bin/ci-info sha1)" = "$GITHUB_SHA"
  test_windows:
    strategy:
      matrix:
        operating-system:
          - windows-latest
        php-versions:
          - '7.2'
          - '7.3'
          - '7.4'
    name: PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: 'composer:v1'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: composer install --no-dev --no-progress --no-suggest --classmap-authoritative --no-ansi --no-interaction
      - name: Configure environment
        run: |
          $ErrorActionPreference = 'stop'
      - name: Check engine
        run: |
          if ("$(.\bin\ci-info driver)" -ne 'github-actions') { throw }
      - name: Check tag creation
        if: github.event_name == 'create'
        run: |
          if ("$(.\bin\ci-info event)" -ne 'tag') { throw }
          if ("$(.\bin\ci-info sha1)" -ne $Env:GITHUB_SHA) { throw }
          $tagName="$(.\bin\ci-info tag:name)"
          if (-not("refs/tags/$tagName" -ceq $Env:GITHUB_REF)) { throw }
      - name: Check pull_request events
        if: github.event_name == 'pull_request'
        run: |
          if ("$(.\bin\ci-info event)" -ne 'pull-request') { throw }
          if ("$(.\bin\ci-info sha1)" -ne $Env:GITHUB_SHA) { throw }
          $range="$(.\bin\ci-info pr:range)"
          if (-not($range -match '^[a-f0-9]{40}\.\.\.[a-f0-9]{40}$')) { throw "Invalid range: $range" }
      - name: Check push events
        if: github.event_name == 'push'
        run: |
          if ("$(.\bin\ci-info event)" -ne 'push') { throw }
          if ("$(.\bin\ci-info sha1)" -ne $Env:GITHUB_SHA) { throw }
      - name: Check scheduled events
        if: github.event_name == 'schedule'
        run: |
          if ("$(.\bin\ci-info event)" -ne 'scheduled') { throw }
          if ("$(.\bin\ci-info sha1)" -ne $Env:GITHUB_SHA) { throw }
      - name: Check repository_dispatch events
        if: github.event_name == 'repository_dispatch'
        run: |
          if ("$(.\bin\ci-info event)" -ne 'manual') { throw }
          if ("$(.\bin\ci-info sha1)" -ne $Env:GITHUB_SHA) { throw }
